joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

#controladores de posicion
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link_link_01
  pid: {p: 10,i: 0,d: 0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_01_link_02
  pid: {p: 10,i: 0,d: 0}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_02_link_03
  pid: {p: 10,i: 0,d: 0}
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link_link_04
  pid: {p: 10,i: 0,d: 0}
joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_04_link_05
  pid: {p: 10,i: 0,d: 0}
joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_05_link_06
  pid: {p: 10,i: 0,d: 0}



